#!/bin/bash

MEDIA_PATH="/mnt/media/"
CONFIG_PATH="/mnt/docker/config/"
DOWNLOAD_PATH="/mnt/downloads/"
PUID=0
PGID=0

function launch_container() {
    echo "Launching $1!"
    echo docker run -d --restart unless-stopped --name $1 $2 | bash
}

function sonarr() {
    launch_container "sonarr" "--link=sabnzbd:sabnzbd -p 8989:8989 -e PUID=$PUID -e PGID=$PGID -v ${CONFIG_PATH}/sonarr:/config -v ${MEDIA_PATH}TV/:/tv -v ${DOWNLOAD_PATH}complete:/complete-downloads linuxserver/sonarr"
}

function radarr() {
    launch_container "radarr" "--link=sabnzbd:sabnzbd -p 7878:7878 -e PUID=$PUID -e PGID=$PGID -v ${CONFIG_PATH}/radarr:/config -v ${MEDIA_PATH}Movies/:/movies -v ${DOWNLOAD_PATH}complete:/complete-downloads linuxserver/radarr"
}

function sabnzbd() {
    launch_container "sabnzbd" "-v ${CONFIG_PATH}/sabnzbd:/config -v ${DOWNLOAD_PATH}complete:/complete-downloads -v ${DOWNLOAD_PATH}incomplete:/incomplete-downloads -e PGID=$PGID -e PUID=$PUID -p 8080:8080 -p 9090:9191 linuxserver/sabnzbd"
   # launch_container "sabnzbd" "-v ${CONFIG_PATH}/sabnzbd:/config -v ${DOWNLOAD_PATH}complete:/complete-downloads -v ${DOWNLOAD_PATH}incomplete:/incomplete-downloads -e PGID=$PGID -e PUID=$PUID -p 8080:8080 -p 9090:9090 linuxserver/sabnzbd"
}

function plex() {
    launch_container "plex" "-p 32400:32400 -e VERSION=latest -e PUID=$PUID -e PGID=$PGID -v /tmp:/transcode -v ${CONFIG_PATH}/plex:/config -v ${MEDIA_PATH}:/data/media --device=/dev/dri:/dev/dri linuxserver/plex"
}

function lidarr() {
    launch_container "lidarr" "--link=sabnzbd:sabnzbd -p 8686:8686 -e PUID=$PUID -e PGID=$PGID -v ${CONFIG_PATH}/lidarr:/config -v ${MEDIA_PATH}Music/:/music -v ${DOWNLOAD_PATH}complete/:/complete-downloads linuxserver/lidarr"
}

function ombi() {
    launch_container "ombi" "-e PUID=$PUID -e PGID=$PGID -e TZ=Europe/London -p 3579:3579 -v ${CONFIG_PATH}/ombi:/config linuxserver/ombi"
}

function tautulli() {
    launch_container "tautulli" "-e PUID=$PUID -e PGID=$PGID -e TZ=Europe/London -p 8181:8181 -v ${CONFIG_PATH}/tautulli:/config -v ${CONFIG_PATH}/plex/Library/Application\ Support/Plex\ Media\ Server/Logs:/logs linuxserver/tautulli"
}

function pihole() {
	launch_container "pihole" "-p 53:53/tcp -p 53:53/udp -p 81:80 -p 444:443 -e TZ=Europe/London -v "${CONFIG_PATH}/pihole/etc-pihole/:/etc/pihole/" -v "${CONFIG_PATH}/pihole/etc-dnsmasq.d/:/etc/dnsmasq.d/" --dns=127.0.0.1 --dns=8.8.8.8 --hostname pi.hole -e VIRTUAL_HOST="pi.hole" -e PROXY_LOCATION="pi.hole" -e ServerIP="127.0.0.1" pihole/pihole:latest"
}

function hydra() {
    launch_container "hydra" "-e PUID=$PUID -e PGID=$PGID -e TZ=Europe/London -p 5075:5075 -v ${CONFIG_PATH}/hydra:/config -v ${DOWNLOAD_PATH}nzb:/downloads linuxserver/hydra"
}

function nginx() {
    launch_container "nginx" "--net=host -e PUID=$PUID -e PGID=$PGID -e TZ=Europe/London -p 80:80 -p 443:443 -v ${CONFIG_PATH}/nginx:/config linuxserver/nginx"
}

function kill() {
    docker rm -f $(docker ps -a -q); docker rmi $(docker images -q)
}

function all() {
    # hydra
    sabnzbd
    sonarr
    radarr
    plex
    lidarr
    ombi
    pihole
    tautulli
    nginx
}

if [ $# -eq 0 ]
    then
        echo "No arguments supplied"
    else
        $1
fi



